#!/bin/sh
rm ../data/all_data_cut/曲奇饼干/.DS_Store
rm ../data/all_data_cut/地三鲜/.DS_Store
rm ../data/all_data_cut/香辣虾/.DS_Store
rm ../data/all_data_cut/蛋包饭/.DS_Store
rm ../data/all_data_cut/清蒸鲈鱼/.DS_Store
rm ../data/all_data_cut/豆角肉丝/.DS_Store
rm ../data/all_data_cut/蛋挞/.DS_Store
rm ../data/all_data_cut/酸菜鱼/.DS_Store
rm ../data/all_data_cut/凉皮/.DS_Store
rm ../data/all_data_cut/麻辣香锅/.DS_Store
rm ../data/all_data_cut/肚丝/.DS_Store
rm ../data/all_data_cut/包子/.DS_Store
rm ../data/all_data_cut/鸡鸭胗/.DS_Store
rm ../data/all_data_cut/蛋糕/.DS_Store
rm ../data/all_data_cut/炒蚕豆/.DS_Store
rm ../data/all_data_cut/蚝油生菜/.DS_Store
rm ../data/all_data_cut/杭椒牛柳/.DS_Store
rm ../data/all_data_cut/鸡蛋羹/.DS_Store
rm ../data/all_data_cut/红烧带鱼/.DS_Store
rm ../data/all_data_cut/海带豆腐汤/.DS_Store
rm ../data/all_data_cut/河粉/.DS_Store
rm ../data/all_data_cut/红烧鸡爪/.DS_Store
rm ../data/all_data_cut/羊肉串/.DS_Store
rm ../data/all_data_cut/白斩鸡/.DS_Store
rm ../data/all_data_cut/西红柿炒鸡蛋/.DS_Store
rm ../data/all_data_cut/糖醋里脊/.DS_Store
rm ../data/all_data_cut/酱牛肉/.DS_Store
rm ../data/all_data_cut/酱焖猪蹄/.DS_Store
rm ../data/all_data_cut/莲藕/.DS_Store
rm ../data/all_data_cut/炒花菜/.DS_Store
rm ../data/all_data_cut/红烧肉/.DS_Store
rm ../data/all_data_cut/葱花手抓饼/.DS_Store
rm ../data/all_data_cut/水果沙拉/.DS_Store
rm ../data/all_data_cut/鱿鱼/.DS_Store
rm ../data/all_data_cut/酿苦瓜/.DS_Store
rm ../data/all_data_cut/大盘鸡/.DS_Store
rm ../data/all_data_cut/菠菜猪肝汤/.DS_Store
rm ../data/all_data_cut/红烧狮子头/.DS_Store
rm ../data/all_data_cut/香辣小龙虾/.DS_Store
rm ../data/all_data_cut/炒面/.DS_Store
rm ../data/all_data_cut/卤蛋/.DS_Store
rm ../data/all_data_cut/麻婆豆腐/.DS_Store
rm ../data/all_data_cut/莴笋肉丝/.DS_Store
rm ../data/all_data_cut/椒盐蘑菇/.DS_Store
rm ../data/all_data_cut/咕噜肉/.DS_Store
rm ../data/all_data_cut/披萨/.DS_Store
rm ../data/all_data_cut/饼干/.DS_Store
rm ../data/all_data_cut/清炒虾仁/.DS_Store
rm ../data/all_data_cut/干煸豆角/.DS_Store
rm ../data/all_data_cut/京酱肉丝/.DS_Store
rm ../data/all_data_cut/紫菜蛋花汤/.DS_Store
rm ../data/all_data_cut/乌鸡汤/.DS_Store
rm ../data/all_data_cut/肉末茄子/.DS_Store
rm ../data/all_data_cut/油条/.DS_Store
rm ../data/all_data_cut/锅包肉/.DS_Store
rm ../data/all_data_cut/薯条/.DS_Store
rm ../data/all_data_cut/泡椒凤爪/.DS_Store
rm ../data/all_data_cut/炒空心菜/.DS_Store
rm ../data/all_data_cut/韭菜炒鸡蛋/.DS_Store
rm ../data/all_data_cut/松鼠桂鱼/.DS_Store
rm ../data/all_data_cut/冰糖雪梨/.DS_Store
rm ../data/all_data_cut/凉拌海带丝/.DS_Store
rm ../data/all_data_cut/肉夹馍/.DS_Store
rm ../data/all_data_cut/家常豆腐/.DS_Store
rm ../data/all_data_cut/鲫鱼豆腐汤/.DS_Store
rm ../data/all_data_cut/葱爆羊肉/.DS_Store
rm ../data/all_data_cut/剁椒鱼头/.DS_Store
rm ../data/all_data_cut/辣子鸡/.DS_Store
rm ../data/all_data_cut/宫保鸡丁/.DS_Store
rm ../data/all_data_cut/松仁玉米/.DS_Store
rm ../data/all_data_cut/粉蒸排骨/.DS_Store
rm ../data/all_data_cut/回锅肉/.DS_Store
rm ../data/all_data_cut/黄瓜炒鸡蛋/.DS_Store
rm ../data/all_data_cut/凉拌西红柿/.DS_Store
rm ../data/all_data_cut/南瓜饼/.DS_Store
rm ../data/all_data_cut/木须肉/.DS_Store
rm ../data/all_data_cut/口水鸡/.DS_Store
rm ../data/all_data_cut/梅菜扣肉/.DS_Store
rm ../data/all_data_cut/皮蛋瘦肉粥/.DS_Store
rm ../data/all_data_cut/汤圆/.DS_Store
rm ../data/all_data_cut/紫菜包饭/.DS_Store
rm ../data/all_data_cut/青椒肉丝/.DS_Store
rm ../data/all_data_cut/可乐鸡翅/.DS_Store
rm ../data/all_data_cut/红薯粥/.DS_Store
rm ../data/all_data_cut/疙瘩汤/.DS_Store
rm ../data/all_data_cut/培根金针菇卷/.DS_Store
rm ../data/all_data_cut/鱼香肉丝/.DS_Store
rm ../data/all_data_cut/玉米棒/.DS_Store
rm ../data/all_data_cut/虾仁西兰花/.DS_Store
rm ../data/all_data_cut/烧麦/.DS_Store
rm ../data/all_data_cut/拔丝山药/.DS_Store
rm ../data/all_data_cut/皮皮虾/.DS_Store
rm ../data/all_data_cut/肠粉/.DS_Store
rm ../data/all_data_cut/手撕包菜/.DS_Store
rm ../data/all_data_cut/蚂蚁上树/.DS_Store
rm ../data/all_data_cut/酸辣土豆丝/.DS_Store
rm ../data/all_data_cut/醋溜白菜/.DS_Store
